### PR TITLE
fix: improve error logs for evaluation failure

### LINKED ISSUE #275: Improve error logs when flag evaluation failed
Current SDK emits following log line when a flag evaluation fails, 

`Unable to correctly evaluate flag with key <flag_key> due to exception <exception_message>`

Ex:- from Java getting started guide when flagd is not up and running 

image

This error hides the exception stack trace, making it difficult to debug errors. 

**Proposal** 

Include the stack trace for better error details

### PR DESCRIPTION
**Pull request by Kavindu-Dodan**
## This PR

Fixes #275

Consider the following log entry with detailed logs explaining the underlying issue by logging stacktrace, 

image

### CODE REVIEW

File: src/main/java/dev/openfeature/sdk/OpenFeatureClient.java [hunk 1]
```diff
@@ -137,7 +137,7 @@ private <T> FlagEvaluationDetails<T> evaluateFlag(FlagValueType type, String key
             details = FlagEvaluationDetails.from(providerEval, key);
             hookSupport.afterHooks(type, hookCtx, details, mergedHooks, hints);
         } catch (Exception e) {
-            log.error("Unable to correctly evaluate flag with key {} due to exception {}", key, e.getMessage());
+            log.error("Unable to correctly evaluate flag with key '{}'", key, e);
```
Comment (toddbaert) [inline src/main/java/dev/openfeature/sdk/OpenFeatureClient.java:140]: This simple change will really help, I agree.

**Review by toddbaert — APPROVED** [review]
