### PR TITLE
fix: MutableContext and ImmutableContext merge are made recursive

### LINKED ISSUE #270: Evaluation context `merge` implementations should be recursive
If there is a property on this called `myKey`, and it has subkeys, and there's also a property called `myKey` on overridingContext, then the subkeys are lost, instead of merged.

This is un-intuitive and should be correct.

see: https://github.com/open-feature/java-sdk/pull/210/files#r1071367173

### PR DESCRIPTION
**Pull request by javicv**
Signed-off-by: Javier Collado <javicv@gmail.com>

## This PR

- Makes the evaluation context merge recursive for both MutableContext and ImmutableContext

### Related Issues

Fixes #270

### How to test

- A new test method _mergeShouldRetainItsSubkeysWhenOverridingContextHasTheSameKey_ in _dev.openfeature.sdk.ImmutableContextTest_ has been added

### CODE REVIEW

**Comment by toddbaert** [comment]
CI is passing now. I'll take a closer look at this today/tomorrow.

File: src/main/java/dev/openfeature/sdk/ImmutableContext.java [hunk 1]
```diff
@@ -86,10 +87,34 @@ public EvaluationContext merge(EvaluationContext overridingContext) {
...
+        Map<String, Value> merged = new HashMap<>();
+
+        merged.putAll(base);
+        for (Entry<String, Value> overridingEntry : overriding.entrySet()) {
+            String key = overridingEntry.getKey();
+            if (overridingEntry.getValue().isStructure() && merged.containsKey(key) && merged.get(key).isStructure()) {
+                Structure mergedValue = merged.get(key).asStructure();
+                Structure overridingValue = overridingEntry.getValue().asStructure();
+                Map<String, Value> newMap = this.merge(mergedValue.asMap(), overridingValue.asMap());
+                merged.put(key, new Value(new ImmutableContext(newMap)));
```
Comment (toddbaert) [inline src/main/java/dev/openfeature/sdk/ImmutableContext.java:113]: I think we want a new `Structure` here, not a new `Context`.

File: src/main/java/dev/openfeature/sdk/MutableContext.java [hunk 2]
```diff
@@ -92,22 +93,53 @@ public EvaluationContext merge(EvaluationContext overridingContext) {
...
+        Map<String, Value> merged = new HashMap<>();
+
+        merged.putAll(base);
+        for (Entry<String, Value> overridingEntry : overriding.entrySet()) {
+            String key = overridingEntry.getKey();
+            if (overridingEntry.getValue().isStructure() && merged.containsKey(key) && merged.get(key).isStructure()) {
+                Structure mergedValue = merged.get(key).asStructure();
+                Structure overridingValue = overridingEntry.getValue().asStructure();
+                Map<String, Value> newMap = this.merge(mergedValue.asMap(), overridingValue.asMap());
+                merged.put(key, new Value(new MutableContext(newMap)));
```
Comment (toddbaert) [inline src/main/java/dev/openfeature/sdk/MutableContext.java:136]: Same as [above](https://github.com/open-feature/java-sdk/pull/280/files#r1097828419), we want a new structure instance here, not an entire new context.

File: src/main/java/dev/openfeature/sdk/ImmutableContext.java [hunk 3]
```diff
@@ -86,10 +87,34 @@ public EvaluationContext merge(EvaluationContext overridingContext) {
...
     }
+
+    /**
+     * Recursively merges the base map from this EvaluationContext with the passed EvaluationContext.
+     * 
+     * @param base base map to merge
+     * @param overriding overriding map to merge
+     * @return resulting merged map
+     */
+    private Map<String, Value> merge(Map<String, Value> base, Map<String, Value> overriding) {
```
Comment (toddbaert) [inline src/main/java/dev/openfeature/sdk/ImmutableContext.java:103]: Both this, and the similar method in `MutableContext` seem very similar. I think you can extract them both to a common protected default implementation, and somehow extract or economize the instantiation [here](https://github.com/open-feature/java-sdk/pull/280/files#diff-3b1bb0fba16899446d6f2ef99d562c9072f6344156ed7f243910bb8fa27d8f57R113), which seems to be the only difference. You could perhaps use an abstract method for returning a new instance, or pass a lambda or something like that.

**Review by toddbaert — CHANGES_REQUESTED** [review]
Thanks so much @javicv . I think this is good conceptually. See comments in private merge methods.

File: src/test/java/dev/openfeature/sdk/ImmutableContextTest.java [hunk 4]
```diff
@@ -64,4 +65,27 @@ void mergeShouldReturnAllTheValuesFromTheContextWhenOverridingContextIsNull() {
         assertEquals("targeting_key", merge.getTargetingKey());
         assertArrayEquals(new Object[]{"key1", "key2"}, merge.keySet().toArray());
     }
+
+    @DisplayName("Merge should retain subkeys from the existing context when the overriding context has the same targeting key")
+    @Test
+    void mergeShouldRetainItsSubkeysWhenOverridingContextHasTheSameKey() {
+        HashMap<String, Value> attributes = new HashMap<>();
```
Comment (Kavindu-Dodan) [inline src/test/java/dev/openfeature/sdk/ImmutableContextTest.java:72]: Something minor about formatting. Let's have some spaces to separate initializations, method invocations and assertions. Given the length of the test case, current formating makes it little difficult to read :)

File: src/main/java/dev/openfeature/sdk/ImmutableContext.java (hunk 3 above)
Comment (Kavindu-Dodan) [reply src/main/java/dev/openfeature/sdk/ImmutableContext.java:103]: Yes, this is correct & perfect suggestion.

What differ is the context type (mutable vs immutable). This can be easily handled with a functional interface [1]. And I would see this best fitting as a default function exposed from `Structure.java`

In pseudocode, 

```
// Structure.java

default <T extends Structure> void merge(Function<String, T> newFunc, ......args ){

   newStructure.apply(params);

}
```


[1] - https://docs.oracle.com/javase/8/docs/api/java/util/function/Function.html

Comment (javicv) [reply src/main/java/dev/openfeature/sdk/ImmutableContext.java:103]: I would say the default method with the recursive merge should be in `EvaluationContext.java` because `Structure` doesn't have `merge`.

Comment (thiyagu06) [reply src/main/java/dev/openfeature/sdk/ImmutableContext.java:103]: I think the recursive merge is actually merging the two structure. so I would also prefer to keeping it in the `Structure.java`.

File: src/main/java/dev/openfeature/sdk/ImmutableContext.java (hunk 1 above)
Comment (javicv) [reply src/main/java/dev/openfeature/sdk/ImmutableContext.java]: Changed to `ImmutableStructure`

File: src/main/java/dev/openfeature/sdk/ImmutableContext.java (hunk 3 above)
Comment (javicv) [reply src/main/java/dev/openfeature/sdk/ImmutableContext.java]: Moved to `Structure.java` with a `Function<Map<String,Value>, T>` as first parameter.

File: src/main/java/dev/openfeature/sdk/Structure.java [hunk 5]
```diff
@@ -90,4 +93,33 @@ default Object convertValue(Value value) {
         }
         throw new ValueNotConvertableError();
     }
+
+    /**
+     * Recursively merges the base map from this EvaluationContext with the passed EvaluationContext.
+     *
```
Comment (thiyagu06) [inline src/main/java/dev/openfeature/sdk/Structure.java:99]:
```suggestion
     * Recursively merges the base map with the overriding map.
     * 
```

**Comment by toddbaert** [comment]
`Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.20.0:check (run-pmd) on project sdk: You have 3 PMD violations.`

@javicv I will re-review later today, but this looks almost perfect to me! You do have some PMD issues though. Try running `mvn verify` locally to see them (if you have issues, try using JDK 8.

File: src/main/java/dev/openfeature/sdk/MutableContext.java [hunk 6]
```diff
@@ -92,18 +91,25 @@ public EvaluationContext merge(EvaluationContext overridingContext) {
...
         if (overridingContext.getTargetingKey() != null && !overridingContext.getTargetingKey().trim().equals("")) {
-            ec.setTargetingKey(overridingContext.getTargetingKey());
+            newTargetingKey = overridingContext.getTargetingKey();
+        }
+        
+        EvaluationContext ec = null;
+        if (newTargetingKey != null && !newTargetingKey.trim().equals("")) {
+            ec = new MutableContext(newTargetingKey, merged);
+        } else {
+            ec = new MutableContext(merged);
```
Comment (toddbaert) [inline src/main/java/dev/openfeature/sdk/MutableContext.java:112]: @javicv can you add one more test, similar to the other, which doesn't have a `targetingKey`, to cover this case?

Comment (thiyagu06) [reply src/main/java/dev/openfeature/sdk/MutableContext.java:112]: @toddbaert I hope we should look into this scenario or will do one more PR? https://github.com/open-feature/java-sdk/issues/270#issuecomment-1421175077

Comment (javicv) [reply src/main/java/dev/openfeature/sdk/MutableContext.java:112]: > @javicv can you add one more test, similar to the other, which doesn't have a `targetingKey`, to cover this case? I'm OK for merge after this.

New test added

> @toddbaert I hope we should look into this scenario or will do one more PR? [#270 (comment)](https://github.com/open-feature/java-sdk/issues/270#issuecomment-1421175077)

@toddbaert, as I mentioned in [this comment in #270](https://github.com/open-feature/java-sdk/issues/270#issuecomment-1422240459), the current implementation doesn't merge lists, only structures. IMHO, merging lists is a different issue, I can take care of it, but we need to clarify if we want to merge lists or simply, as it's now, override the existing list with the new one.

Comment (toddbaert) [reply src/main/java/dev/openfeature/sdk/MutableContext.java:112]: I don't think lists should be merged at all. Merging nested structures is a common use case. I would not expect lists/sets to be merged, but overwritten.

File: src/test/java/dev/openfeature/sdk/ImmutableContextTest.java [hunk 7]
```diff
@@ -64,4 +65,54 @@ void mergeShouldReturnAllTheValuesFromTheContextWhenOverridingContextIsNull() {
...
+    @Test
+    void mergeShouldRetainItsSubkeysWhenOverridingContextHasNoTargetingKey() {
+        HashMap<String, Value> attributes = new HashMap<>();
+        HashMap<String, Value> key1Attributes = new HashMap<>();
+
+        key1Attributes.put("key1_1", new Value("val1_1"));
+        attributes.put("key1", new Value(new ImmutableStructure(key1Attributes)));
+        attributes.put("key2", new Value("val2"));
+        
+        EvaluationContext ctx = new ImmutableContext("targeting_key", attributes);
```
Comment (toddbaert) [inline src/test/java/dev/openfeature/sdk/ImmutableContextTest.java:106]:
```suggestion
        EvaluationContext ctx = new ImmutableContext(attributes);
```

File: src/test/java/dev/openfeature/sdk/ImmutableContextTest.java [hunk 8]
```diff
@@ -64,4 +65,54 @@ void mergeShouldReturnAllTheValuesFromTheContextWhenOverridingContextIsNull() {
...
+        HashMap<String, Value> key1Attributes = new HashMap<>();
+
+        key1Attributes.put("key1_1", new Value("val1_1"));
+        attributes.put("key1", new Value(new ImmutableStructure(key1Attributes)));
+        attributes.put("key2", new Value("val2"));
+        
+        EvaluationContext ctx = new ImmutableContext(attributes);
+        EvaluationContext overriding = new ImmutableContext("");
+        EvaluationContext merge = ctx.merge(overriding);
+        assertEquals("targeting_key", merge.getTargetingKey());
```
Comment (toddbaert) [inline src/test/java/dev/openfeature/sdk/ImmutableContextTest.java:109]:
```suggestion
```

File: src/test/java/dev/openfeature/sdk/ImmutableContextTest.java [hunk 9]
```diff
@@ -64,4 +65,53 @@ void mergeShouldReturnAllTheValuesFromTheContextWhenOverridingContextIsNull() {
...
+    void mergeShouldRetainItsSubkeysWhenOverridingContextHasNoTargetingKey() {
+        HashMap<String, Value> attributes = new HashMap<>();
+        HashMap<String, Value> key1Attributes = new HashMap<>();
+
+        key1Attributes.put("key1_1", new Value("val1_1"));
+        attributes.put("key1", new Value(new ImmutableStructure(key1Attributes)));
+        attributes.put("key2", new Value("val2"));
+        
+        EvaluationContext ctx = new ImmutableContext(attributes);
+        EvaluationContext overriding = new ImmutableContext("");
```
Comment (toddbaert) [inline src/test/java/dev/openfeature/sdk/ImmutableContextTest.java:107]:
```suggestion
        EvaluationContext overriding = new ImmutableContext();
```

**Comment by toddbaert** [comment]
@javicv I pushed some (very) small changes to your second test that I think should resolve the coverage issue.

**Review by toddbaert — APPROVED** [review]
I'm a bit confused my codecov isn't seeing that one line covered, but I'm satisfied with the tests, and the delta is very small anyway.

Thanks @javicv for all your efforts! This will be really nice to have. Approved.

**Review by beeme1mr — APPROVED** [review]

**Review by Kavindu-Dodan — APPROVED** [review]
